### ISSUE TITLE
Does it support memcached?

### ISSUE THREAD

**Issue by Husain136** [swayok/alternative-laravel-cache#23]

**Comment by swayok** [comment]
No.

**Comment by Husain136** [comment]
Will it ever will?

**Comment by swayok** [comment]
Hi. I've added `memcached` support but I cannot test it because my dev PC is on Windows and there are no `memcached` extension available (only outdataed `memcache` extension which is not supported by Laravel).
Also I've refactored tests so that you can run them from inside package (do `composer update` and run tests as usual).
It should work because I used Laravel's code to get connection and pass it to cache store provided by `php-cache/memcached-adapter`.
I'd like to have a feedback about if it works or not.
