### ISSUE TITLE
can not use laravel 10 Pruning Stale Cache Tags

### ISSUE THREAD

**Issue by fripig** [swayok/alternative-laravel-cache#45]
https://laravel.com/docs/10.x/cache#pruning-stale-cache-tags

run cache:prune-stale-tags will get this message

```
   ERROR  Pruning cache tags is only necessary when using Redis.
```

**Comment by swayok** [comment]
Tags are managed by drivers from https://www.php-cache.com/. cache:prune-stale-tags command will not work because tags handling is totally different from Laravel's. I reviewed docs about tags on php-cache.com and haven't found any mentioning about the need to prune stale tags or possibility to to that. I'm using this lib for years and haven't met any problems with stale tags. 
They actually recommend to use hierarchial cache with Redis - then there will be no extra records stored in Redis to handle tagging.
